# Simple workflow for deploying static content to GitHub Pages
name: Update readme and page

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Data generation job
  generate-data:
    runs-on: ubuntu-latest
    outputs:
      data-generated: ${{ steps.generate.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install arxiv
      - name: Generate data and README
        id: generate
        run: |
          cd scripts
          python export_data.py
          python export_readme.py
          echo "success=true" >> $GITHUB_OUTPUT
      - name: Prepare assets
        run: |
          mkdir -p page/src/assets
          cp data/data.json page/src/assets/
      - name: Upload generated data
        uses: actions/upload-artifact@v4
        with:
          name: generated-data
          path: page/src/assets/data.json
      - name: Commit and push README updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Auto-update README with latest data" || echo "No README changes to commit"
          git push

  # Deploy job
  deploy:
    needs: generate-data
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download generated data
        uses: actions/download-artifact@v4
        with:
          name: generated-data
          path: page/src/assets/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './page/package-lock.json'
      - name: Install dependencies
        run: |
          cd page
          npm install
      - name: Build and Export Next.js
        run: |
          cd page
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './page/out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
